-- Homework1
-- 1. Create DEA table, load the data, and create indexes.
-- 1a (2 points).
CREATE TABLE CSE532.DEA_NY
(
    REPORTER_DEA_NO VARCHAR(128),
    REPORTER_BUS_ACT VARCHAR(128),
    REPORTER_NAME VARCHAR(128),
    REPORTER_ADDL_CO_INFO VARCHAR(128),
    REPORTER_ADDRESS1 VARCHAR(128),
    REPORTER_ADDRESS2 VARCHAR(128),
    REPORTER_CITY VARCHAR(128),
    REPORTER_STATE VARCHAR(128),
    REPORTER_ZIP VARCHAR(5),
    REPORTER_COUNTY VARCHAR(128),
    BUYER_DEA_NO VARCHAR(128),
    BUYER_BUS_ACT VARCHAR(128),
    BUYER_NAME VARCHAR(128),
    BUYER_ADDL_CO_INFO VARCHAR(128),
    BUYER_ADDRESS1 VARCHAR(128),
    BUYER_ADDRESS2 VARCHAR(128),
    BUYER_CITY VARCHAR(128),
    BUYER_STATE VARCHAR(128),
    BUYER_ZIP VARCHAR(5),
    BUYER_COUNTY VARCHAR(128),
    TRANSACTION_CODE VARCHAR(128),
    DRUG_CODE VARCHAR(4),
    NDC_NO VARCHAR(128),
    DRUG_NAME VARCHAR(128),
    QUANTITY FLOAT(10),
    UNIT VARCHAR(128),
    ACTION_INDICATOR VARCHAR(128),
    ORDER_FORM_NO VARCHAR(128),
    CORRECTION_NO VARCHAR(128),
    STRENGTH VARCHAR(128),
    TRANSACTION_DATE DATE NULL,
    CALC_BASE_WT_IN_GM DECIMAL(10),
    DOSAGE_UNIT DECIMAL(10),
    TRANSACTION_ID VARCHAR(128),
    PRODUCT_NAME VARCHAR(128),
    INGREDIENT_NAME VARCHAR(128),
    MEASURE VARCHAR(128),
    MME_CONVERSION_FACTOR  DECIMAL(10),
    COMBINED_LABELER_NAME VARCHAR(128),
    REPORTER_FAMILY VARCHAR(128),
    DOS_STR DECIMAL(10),
    MME DECIMAL(10)
) COMPRESS YES;

SELECT SUM(DOSAGE_UNIT) FROM CSE532.DEA_NY;
SELECT * FROM CSE532.DEA_NY;