-- 1e : facilityinsert.sql

ALTER TABLE CSE532.FACILITYORIGINAL ADD COLUMN GEOLOCATION DB2GSE.ST_POINT;

UPDATE CSE532.FACILITYORIGINAL
SET GEOLOCATION = DB2GSE.ST_POINT(LATITUDE,LONGITUDE,1);


insert into CSE532.facility(FACILITYID, FACILITYNAME, DESCRIPTION,
                            ADDRESS1, ADDRESS2, CITY, STATE, ZIPCODE,
                            COUNTYCODE, COUNTY, GEOLOCATION)
select FACILITYID, FACILITYNAME, DESCRIPTION,
       ADDRESS1, ADDRESS2, CITY, STATE, ZIPCODE,
       COUNTYCODE, COUNTY,GEOLOCATION from CSE532.facilityoriginal;
