SQL3501W  The table space(s) in which the table resides will not be placed in 
backup pending state since forward recovery is disabled for the database.

SQL3109N  The utility is beginning to load data from file 
"/home/hang/cse532/hw3/Health_Facility_General_Information.csv".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/22/2020 
14:22:25.367518".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "3831" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "3831".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "03/22/2020 
14:22:26.386576".

SQL3500W  The utility is beginning the "BUILD" phase at time "03/22/2020 
14:22:26.447163".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "03/22/2020 
14:22:27.711543".


Number of rows read         = 3831
Number of rows skipped      = 0
Number of rows loaded       = 3831
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 3831

SQL3304N  The table does not exist.

SQL3304N  The table does not exist.

SQL3501W  The table space(s) in which the table resides will not be placed in 
backup pending state since forward recovery is disabled for the database.

SQL3109N  The utility is beginning to load data from file 
"/home/hang/cse532/hw3/Health_Facility_Certification_Information.csv".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/22/2020 
16:02:46.161551".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3123W  The field value in row "F0-1" and column "6" cannot be converted to 
a PACKED DECIMAL value.  A null was loaded.

SQL3227W  Record token "F0-1" refers to user record number "1".

SQL3125W  The character data in row "F1-2300" and column "2" was truncated 
because the data is longer than the target database column.

SQL3125W  The character data in row "F1-2301" and column "2" was truncated 
because the data is longer than the target database column.

SQL3125W  The character data in row "F1-2302" and column "2" was truncated 
because the data is longer than the target database column.

SQL3125W  The character data in row "F1-2303" and column "2" was truncated 
because the data is longer than the target database column.

SQL3125W  The character data in row "F1-2304" and column "2" was truncated 
because the data is longer than the target database column.

SQL3227W  Record token "F1-2300" refers to user record number "15596".

SQL3227W  Record token "F1-2301" refers to user record number "15597".

SQL3227W  Record token "F1-2302" refers to user record number "15598".

SQL3227W  Record token "F1-2303" refers to user record number "15599".

SQL3227W  Record token "F1-2304" refers to user record number "15600".

SQL3110N  The utility has completed processing.  "29456" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "29456".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "03/22/2020 
16:02:48.223832".

SQL3500W  The utility is beginning the "BUILD" phase at time "03/22/2020 
16:02:48.297377".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "03/22/2020 
16:02:54.187520".

SQL3500W  The utility is beginning the "DELETE" phase at time "03/22/2020 
16:02:54.891366".

SQL3509W  The utility has deleted "25627" rows from the table.

SQL3515W  The utility has finished the "DELETE" phase at time "03/22/2020 
16:03:05.717516".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 29456
Number of rows skipped      = 0
Number of rows loaded       = 29456
Number of rows rejected     = 0
Number of rows deleted      = 25627
Number of rows committed    = 29456

SQL3501W  The table space(s) in which the table resides will not be placed in 
backup pending state since forward recovery is disabled for the database.

SQL3109N  The utility is beginning to load data from file 
"/home/hang/cse532/hw3/Health_Facility_Certification_Information.csv".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/22/2020 
16:15:19.332947".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3123W  The field value in row "F0-1" and column "6" cannot be converted to 
a PACKED DECIMAL value.  A null was loaded.

SQL3227W  Record token "F0-1" refers to user record number "1".

SQL3125W  The character data in row "F1-2300" and column "2" was truncated 
because the data is longer than the target database column.

SQL3125W  The character data in row "F1-2301" and column "2" was truncated 
because the data is longer than the target database column.

SQL3125W  The character data in row "F1-2302" and column "2" was truncated 
because the data is longer than the target database column.

SQL3125W  The character data in row "F1-2303" and column "2" was truncated 
because the data is longer than the target database column.

SQL3125W  The character data in row "F1-2304" and column "2" was truncated 
because the data is longer than the target database column.

SQL3227W  Record token "F1-2300" refers to user record number "15596".

SQL3227W  Record token "F1-2301" refers to user record number "15597".

SQL3227W  Record token "F1-2302" refers to user record number "15598".

SQL3227W  Record token "F1-2303" refers to user record number "15599".

SQL3227W  Record token "F1-2304" refers to user record number "15600".

SQL3110N  The utility has completed processing.  "29456" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "29456".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "03/22/2020 
16:15:20.554359".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 29456
Number of rows skipped      = 0
Number of rows loaded       = 29456
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 29456

SQL3501W  The table space(s) in which the table resides will not be placed in 
backup pending state since forward recovery is disabled for the database.

SQL3109N  The utility is beginning to load data from file 
"/home/hang/cse532/hw3/Health_Facility_Certification_Information.csv".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/24/2020 
20:42:11.390329".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3123W  The field value in row "F0-1" and column "6" cannot be converted to 
a PACKED DECIMAL value.  A null was loaded.

SQL3227W  Record token "F0-1" refers to user record number "1".

SQL3125W  The character data in row "F1-2300" and column "2" was truncated 
because the data is longer than the target database column.

SQL3125W  The character data in row "F1-2301" and column "2" was truncated 
because the data is longer than the target database column.

SQL3125W  The character data in row "F1-2302" and column "2" was truncated 
because the data is longer than the target database column.

SQL3125W  The character data in row "F1-2303" and column "2" was truncated 
because the data is longer than the target database column.

SQL3125W  The character data in row "F1-2304" and column "2" was truncated 
because the data is longer than the target database column.

SQL3227W  Record token "F1-2300" refers to user record number "15596".

SQL3227W  Record token "F1-2301" refers to user record number "15597".

SQL3227W  Record token "F1-2302" refers to user record number "15598".

SQL3227W  Record token "F1-2303" refers to user record number "15599".

SQL3227W  Record token "F1-2304" refers to user record number "15600".

SQL3110N  The utility has completed processing.  "29456" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "29456".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "03/24/2020 
20:42:12.553729".

SQL3500W  The utility is beginning the "BUILD" phase at time "03/24/2020 
20:42:12.620655".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "03/24/2020 
20:42:18.932599".

SQL3500W  The utility is beginning the "DELETE" phase at time "03/24/2020 
20:42:19.653959".

SQL3509W  The utility has deleted "25627" rows from the table.

SQL3515W  The utility has finished the "DELETE" phase at time "03/24/2020 
20:42:30.196730".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 29456
Number of rows skipped      = 0
Number of rows loaded       = 29456
Number of rows rejected     = 0
Number of rows deleted      = 25627
Number of rows committed    = 29456

SQL3501W  The table space(s) in which the table resides will not be placed in 
backup pending state since forward recovery is disabled for the database.

SQL3109N  The utility is beginning to load data from file 
"/home/hang/cse532/hw3/Health_Facility_Certification_Information.csv".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/24/2020 
20:43:01.880384".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3123W  The field value in row "F0-1" and column "6" cannot be converted to 
a PACKED DECIMAL value.  A null was loaded.

SQL3227W  Record token "F0-1" refers to user record number "1".

SQL3125W  The character data in row "F1-2300" and column "2" was truncated 
because the data is longer than the target database column.

SQL3125W  The character data in row "F1-2301" and column "2" was truncated 
because the data is longer than the target database column.

SQL3125W  The character data in row "F1-2302" and column "2" was truncated 
because the data is longer than the target database column.

SQL3125W  The character data in row "F1-2303" and column "2" was truncated 
because the data is longer than the target database column.

SQL3125W  The character data in row "F1-2304" and column "2" was truncated 
because the data is longer than the target database column.

SQL3227W  Record token "F1-2300" refers to user record number "15596".

SQL3227W  Record token "F1-2301" refers to user record number "15597".

SQL3227W  Record token "F1-2302" refers to user record number "15598".

SQL3227W  Record token "F1-2303" refers to user record number "15599".

SQL3227W  Record token "F1-2304" refers to user record number "15600".

SQL3110N  The utility has completed processing.  "29456" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "29456".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "03/24/2020 
20:43:03.043920".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 29456
Number of rows skipped      = 0
Number of rows loaded       = 29456
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 29456

