-- 3. (3 points) Write a query noerzips.sql to find zip codes without any
-- "Emergency Department", neither in their neighboring zip codes.

-- Case 1: zipcode in facility which does not have Emergency Department or is not next to Emergency Department

WITH FIRST AS ( SELECT SUBSTR(A.ZIPCODE,1,5) AS ZIPCODE FROM CSE532.FACILITY AS A INNER JOIN CSE532.facilitycertification AS B
        ON A.FACILITYID = B.FacilityID WHERE B.AttributeValue = 'Emergency Department' ),
SECOND AS (SELECT SUBSTR(ZCTA5CE10, 1, 5) AS ZIPCODE,SHAPE FROM CSE532.USZIP WHERE ZCTA5CE10 IN (SELECT ZIPCODE FROM FIRST)),
NY_ZIP AS (SELECT SUBSTR(GEOID10,1,5) AS GEOID10,SHAPE FROM CSE532.USZIP WHERE ZCTA5CE10 IN (SELECT SUBSTR(ZIPCODE, 1, 5) FROM CSE532.FACILITY)),
THIRD AS(SELECT ZIPCODE FROM SECOND UNION (SELECT GEOID10 FROM NY_ZIP ZIPC, SECOND NZIPC WHERE DB2GSE.ST_Touches(ZIPC.SHAPE,NZIPC.SHAPE) = 1))
SELECT GEOID10 AS ZIPCODE FROM NY_ZIP WHERE GEOID10 NOT IN (SELECT ZIPCODE FROM THIRD);

-- Case 2: zipcode in uszip in New York which does not have Emergency Department or is not next to Emergency Department

WITH FIRST AS ( SELECT SUBSTR(A.ZIPCODE,1,5) AS ZIPCODE FROM CSE532.FACILITY AS A INNER JOIN CSE532.facilitycertification AS B
        ON A.FACILITYID = B.FacilityID WHERE B.AttributeValue = 'Emergency Department' ),
SECOND AS (SELECT SUBSTR(ZCTA5CE10, 1, 5) AS ZIPCODE,SHAPE FROM CSE532.USZIP WHERE ZCTA5CE10 IN (SELECT ZIPCODE FROM FIRST)),
NY_ZIP AS (SELECT SUBSTR(GEOID10,1,5) AS GEOID10,SHAPE FROM CSE532.USZIP WHERE ZCTA5CE10 >10000 AND ZCTA5CE10 <= 14975),
THIRD AS(SELECT ZIPCODE FROM SECOND UNION (SELECT GEOID10 FROM NY_ZIP ZIPC, SECOND NZIPC WHERE DB2GSE.ST_Touches(ZIPC.SHAPE,NZIPC.SHAPE) = 1))
SELECT GEOID10 AS ZIPCODE FROM NY_ZIP WHERE GEOID10 NOT IN (SELECT ZIPCODE FROM THIRD);
