SQL3501W  The table space(s) in which the table resides will not be placed in 
backup pending state since forward recovery is disabled for the database.

SQL3109N  The utility is beginning to load data from file 
"/home/hang/cse532/hw3/nyzip.csv".

SQL3500W  The utility is beginning the "LOAD" phase at time "04/02/2020 
22:09:56.733355".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3124W  The field value in row "F0-1" and column "1" cannot be converted to 
a PACKED DECIMAL value, but the target column is not nullable.  The row was 
not loaded.

SQL3185W  The previous error occurred while processing data from row "F0-1" of 
the input file.

SQL3227W  Record token "F0-1" refers to user record number "1".

SQL3110N  The utility has completed processing.  "44411" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "44411".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "04/02/2020 
22:09:57.903000".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 44411
Number of rows skipped      = 0
Number of rows loaded       = 44410
Number of rows rejected     = 1
Number of rows deleted      = 0
Number of rows committed    = 44411

SQL3501W  The table space(s) in which the table resides will not be placed in 
backup pending state since forward recovery is disabled for the database.

SQL3109N  The utility is beginning to load data from file 
"/home/hang/cse532/hw3/nyzip.csv".

SQL3500W  The utility is beginning the "LOAD" phase at time "04/04/2020 
11:16:21.834109".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3124W  The field value in row "F0-1" and column "1" cannot be converted to 
a PACKED DECIMAL value, but the target column is not nullable.  The row was 
not loaded.

SQL3185W  The previous error occurred while processing data from row "F0-1" of 
the input file.

SQL3227W  Record token "F0-1" refers to user record number "1".

SQL3110N  The utility has completed processing.  "44411" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "44411".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "04/04/2020 
11:16:22.829483".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 44411
Number of rows skipped      = 0
Number of rows loaded       = 44410
Number of rows rejected     = 1
Number of rows deleted      = 0
Number of rows committed    = 44411

SQL3501W  The table space(s) in which the table resides will not be placed in 
backup pending state since forward recovery is disabled for the database.

SQL3109N  The utility is beginning to load data from file 
"/home/hang/cse532/hw3/nyzip.csv".

SQL3500W  The utility is beginning the "LOAD" phase at time "04/04/2020 
11:29:03.564636".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3124W  The field value in row "F0-1" and column "1" cannot be converted to 
a PACKED DECIMAL value, but the target column is not nullable.  The row was 
not loaded.

SQL3185W  The previous error occurred while processing data from row "F0-1" of 
the input file.

SQL3227W  Record token "F0-1" refers to user record number "1".

SQL3110N  The utility has completed processing.  "44411" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "44411".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "04/04/2020 
11:29:04.505705".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 44411
Number of rows skipped      = 0
Number of rows loaded       = 44410
Number of rows rejected     = 1
Number of rows deleted      = 0
Number of rows committed    = 44411

