-- Homework2

CREATE PROCEDURE CSE532.calculate_salary(OUT std DOUBLE)
LANGUAGE SQL
BEGIN
    DECLARE SUM DOUBLE;
    DECLARE VAR DOUBLE;
    DECLARE SUMMATION DOUBLE;
    DECLARE LEN INTEGER;
    DECLARE CURRENT1 DOUBLE;
    DECLARE SQLSTATE CHAR(5);
    DECLARE c CURSOR FOR
        SELECT SALARY FROM EMPLOYEE;

    OPEN c;

    FETCH c INTO CURRENT1;
    SET LEN = 0;
    SET SUM = 0;
    SET SUMMATION = 0;
    SET STD = 0;
    WHILE(SQLSTATE = '00000') DO
        SET SUM = SUM + CURRENT1 * CURRENT1;
        SET SUMMATION = SUMMATION + CURRENT1;
        SET LEN = LEN +1;
        FETCH c INTO CURRENT1;
    END WHILE;

    SET SUM = SUM / LEN;
    SET SUMMATION = SUMMATION / LEN;
    SET VAR = SUM - SUMMATION * SUMMATION;
    SET std = SQRT(STD);
END@

call CSE532.calculate_salary(?)@